title: OpenShift AI Sandboxのクイックスタート
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://akubicharm.github.io

aux_links:
  Developer Sandbox: https://developers.redhat.com/developer-sandbox

enable_copy_code_button: true  

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
  
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false 